version: '3.8'

services:
  backend:
    build: ../qwerx-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/qwerx
      - SPRING_DATASOURCE_USERNAME=qwerx
      - SPRING_DATASOURCE_PASSWORD=qwerx
    networks:
      - qwerx-net
    depends_on:
      - postgres

  frontend:
    build: ../qwerx-frontend
    ports:
      - "4200:4200"
    volumes:
      - ../qwerx-frontend:/app
      - /app/node_modules
    networks:
      - qwerx-net

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
    networks:
      - qwerx-net

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: qwerx
      POSTGRES_PASSWORD: qwerx
      POSTGRES_DB: qwerx
    ports:
      - "5433:5432"
    networks:
      - qwerx-net
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  qwerx-net:
    driver: bridge

volumes:
  postgres_data:
    driver: local
